### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by soamze**

### CODE REVIEW

**Comment by sondosalfukaha** [comment]
Edit the title please

**Comment by soamze** [comment]
I edit the title

**Review by sondosalfukaha — CHANGES_REQUESTED** [review]
edit the title to "Ertwaa" **Not "Ertwaa Project"**

**Review by sondosalfukaha — APPROVED** [review]
Good Job

**Review by sondosalfukaha — APPROVED** [review]
Good Job

**Pull request merged**
